// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'day': string;
  'icon': string;
  'locationBox': string;
  'locationName': string;
  'locationPlaceDetails': string;
}
export const cssExports: CssExports;
export default cssExports;
