// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'text': string;
  'textBold': string;
  'textCapitalize': string;
  'weatherIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
