// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'icon': string;
  'locationWeatherDetails': string;
  'temperature': string;
}
export const cssExports: CssExports;
export default cssExports;
