// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'border-animate': string;
  'loader': string;
}
export const cssExports: CssExports;
export default cssExports;
