// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeButton': string;
  'closeIcon': string;
  'modal': string;
  'overlay': string;
  'title': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
