// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'loader': string;
  'weatherContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
