// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dayWeatherDetails': string;
  'row': string;
  'rowName': string;
  'rowValue': string;
}
export const cssExports: CssExports;
export default cssExports;
