// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorText': string;
  'notFound': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
